# Generated by Django 5.0.3 on 2024-05-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tl_marks", models.FloatField()),
                ("hr_marks", models.FloatField()),
                ("feedback", models.TextField()),
                ("evaluation_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("username", models.CharField(blank=True, max_length=40)),
                ("password", models.CharField(blank=True, max_length=40)),
                (
                    "employee_id",
                    models.CharField(
                        default="HB-", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("employee_email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=255)),
                ("is_team_lead", models.BooleanField(default=False)),
                (
                    "team_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_employees",
                        to="website.employee",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="website.teams",
                    ),
                ),
            ],
        ),
    ]
