# Generated by Django 5.0.3 on 2024-05-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationformmodel",
            name="employee",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.employee",
            ),
            preserve_default=False,
        ),
    ]
