# Generated by Django 5.0.3 on 2024-05-08 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_evaluationformmodel_evaluated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AlterModelOptions(
            name="evaluationformmodel",
            options={
                "verbose_name": "Evaluation Form",
                "verbose_name_plural": "Evaluation Forms",
            },
        ),
        migrations.AlterModelOptions(
            name="teams",
            options={"verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
    ]
