# Generated by Django 5.0.3 on 2024-05-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="highbit_experience",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="previous_experience",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
