# Generated by Django 5.0.3 on 2024-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_employee_highbit_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationformmodel",
            name="_weighted_average",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
