# Generated by Django 5.0.3 on 2024-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_alter_evaluationformmodel_evaluation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(null=True),
        ),
    ]
