# Generated by Django 5.0.3 on 2024-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_evaluationformmodel_evaluation_for_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminFeautures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_enabling_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="evaluationformmodel",
            name="hr_marks",
            field=models.FloatField(null=True),
        ),
    ]
