# Generated by Django 5.0.3 on 2024-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_adminfeautures_alter_evaluationformmodel_hr_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminfeautures",
            name="form_enabling_date",
            field=models.IntegerField(),
        ),
    ]
