# Generated by Django 5.0.3 on 2024-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_alter_adminfeautures_form_enabling_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationformmodel",
            name="time_stamp",
            field=models.TimeField(auto_now=True),
        ),
    ]
