# Generated by Django 5.0.3 on 2024-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_alter_evaluationformmodel_evaluation_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationformmodel",
            name="previous_month",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="evaluationformmodel",
            name="previous_year",
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name="evaluationformmodel",
            name="evaluation_for",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
