# Generated by Django 5.0.3 on 2024-05-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_remove_employee_highbit_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminfeautures",
            name="enable_weightage_calculation",
            field=models.BooleanField(default=False),
        ),
    ]
