# Generated by Django 5.0.3 on 2024-05-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_alter_adminfeautures_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminfeautures",
            name="enable_weightage_calculation",
        ),
        migrations.AddField(
            model_name="employee",
            name="confirmation_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="website.teams",
            ),
        ),
    ]
