# Generated by Django 5.0.3 on 2024-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_employee_mvp_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="mvp_role",
            field=models.CharField(
                choices=[
                    ("Super", "Super"),
                    ("Planner", "Planner"),
                    ("Developer", "Developer"),
                    ("HR", "HR"),
                    ("TL", "TL"),
                    ("Growth Manager", "Growth Manager"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
