# Generated by Django 5.0.3 on 2024-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_alter_employee_mvp_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="mvp_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Super", "Super"),
                    ("Growth Manager", "Growth Manager"),
                    ("Planner", "Planner"),
                    ("Developer", "Developer"),
                    ("HR", "HR"),
                    ("UI Artist", "UI Artist"),
                    ("Sound Artist", "Sound Artist"),
                    ("Modler", "Modler"),
                    ("Video Editor", "Video Editor"),
                    ("CG Artist", "CG Artist"),
                    ("QA", "QA"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
