# Generated by Django 5.0.3 on 2024-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0024_alter_employee_mvp_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="mvp_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Super", "Super"),
                    ("Growth Manager", "Growth Manager"),
                    ("Team Lead", "Team Lead"),
                    ("Planner", "Planner"),
                    ("Developer", "Developer"),
                    ("HR", "HR"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
