# Generated by Django 5.0.3 on 2024-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0026_employee_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_permanent",
            field=models.BooleanField(default=False),
        ),
    ]
