# Generated by Django 4.0.6 on 2024-07-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_employee_confirmation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEmailsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade_A_bonus', models.FloatField()),
                ('grade_B_bonus', models.FloatField()),
                ('total_bonus', models.FloatField()),
                ('grade_a_employees_count', models.IntegerField(blank=True, null=True)),
                ('grade_b_employees_count', models.IntegerField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.employee')),
            ],
            options={
                'verbose_name': 'Bonus Email History',
                'verbose_name_plural': 'Bonus Emails History',
            },
        ),
    ]
