# Generated by Django 5.0.3 on 2024-09-05 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0029_bonusemailshistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonusemailshistory",
            options={
                "verbose_name": "Bonus Email History",
                "verbose_name_plural": "Bonus Emails History",
            },
        ),
        migrations.RenameField(
            model_name="bonusemailshistory",
            old_name="grade_A_employees_count",
            new_name="grade_a_employees_count",
        ),
        migrations.RenameField(
            model_name="bonusemailshistory",
            old_name="grade_B_employees_count",
            new_name="grade_b_employees_count",
        ),
    ]
