# Generated by Django 4.0.6 on 2024-07-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0025_alter_employee_mvp_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_phase', models.CharField(choices=[('MVP', 'MVP'), ('Product', 'Product')], max_length=100)),
                ('associates', models.ManyToManyField(related_name='associates', to='website.employee')),
                ('developers', models.ManyToManyField(related_name='developers', to='website.employee')),
                ('planners', models.ManyToManyField(related_name='planners', to='website.employee')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.teams')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
            ],
            options={
                'verbose_name': 'MVP',
                'verbose_name_plural': 'MVPs',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('mvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVP.mvp')),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.teams')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
