# Generated by Django 4.0.6 on 2024-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0002_activitytype_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
