# Generated by Django 5.0.3 on 2024-06-12 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0002_alter_mvp_updated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mvp",
            name="updated_by",
        ),
    ]
