# Generated by Django 4.0.6 on 2024-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0003_alter_activitytype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvp',
            name='development_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mvp',
            name='planning_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
