# Generated by Django 5.0.3 on 2024-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0003_remove_mvp_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvp",
            name="name",
            field=models.TextField(),
        ),
    ]
