# Generated by Django 5.0.3 on 2024-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0004_alter_mvp_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
