# Generated by Django 5.0.3 on 2024-06-15 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0005_alter_activity_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "Activity", "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="activitytype",
            options={
                "verbose_name": "Activity Type",
                "verbose_name_plural": "Activity Types",
            },
        ),
        migrations.AlterModelOptions(
            name="mvp",
            options={"verbose_name": "MVP", "verbose_name_plural": "MVPs"},
        ),
    ]
