# Generated by Django 4.0.6 on 2024-07-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_employee_mvp_role'),
        ('MVP', '0005_remove_mvp_planning_starting_date_mvp_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvp',
            name='is_active',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.employee'),
        ),
        migrations.AddField(
            model_name='mvp',
            name='status',
            field=models.CharField(choices=[('Pause', 'Pause'), ('Completed', 'Completed'), ('Active', 'Active')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='mvp',
            name='current_phase',
            field=models.CharField(choices=[('MVP', 'MVP'), ('Product', 'Product'), ('Failed', 'Failed')], default='MVP', max_length=100),
        ),
    ]
