# Generated by Django 4.0.6 on 2024-07-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0007_mvp_first_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
