# Generated by Django 5.0.3 on 2024-06-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0008_remove_mvp_game_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
