# Generated by Django 5.0.3 on 2024-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0009_mvp_plan"),
        ("website", "0024_alter_employee_mvp_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="cg_artist",
            field=models.ManyToManyField(
                related_name="cg_artist", to="website.employee"
            ),
        ),
        migrations.AddField(
            model_name="mvp",
            name="modler",
            field=models.ManyToManyField(related_name="modler", to="website.employee"),
        ),
        migrations.AddField(
            model_name="mvp",
            name="qa",
            field=models.ManyToManyField(related_name="qa", to="website.employee"),
        ),
        migrations.AddField(
            model_name="mvp",
            name="sound_artist",
            field=models.ManyToManyField(
                related_name="sound_artist", to="website.employee"
            ),
        ),
        migrations.AddField(
            model_name="mvp",
            name="ui",
            field=models.ManyToManyField(related_name="ui", to="website.employee"),
        ),
        migrations.AddField(
            model_name="mvp",
            name="video_editor",
            field=models.ManyToManyField(
                related_name="video_editor", to="website.employee"
            ),
        ),
    ]
