# Generated by Django 5.0.3 on 2024-06-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0010_mvp_cg_artist_mvp_modler_mvp_qa_mvp_sound_artist_and_more"),
        ("website", "0024_alter_employee_mvp_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.employee",
            ),
        ),
    ]
