# Generated by Django 5.0.3 on 2024-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0011_mvp_updated_by"),
        ("website", "0024_alter_employee_mvp_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mvp",
            name="cg_artist",
        ),
        migrations.RemoveField(
            model_name="mvp",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mvp",
            name="modler",
        ),
        migrations.RemoveField(
            model_name="mvp",
            name="qa",
        ),
        migrations.RemoveField(
            model_name="mvp",
            name="sound_artist",
        ),
        migrations.RemoveField(
            model_name="mvp",
            name="ui",
        ),
        migrations.RemoveField(
            model_name="mvp",
            name="video_editor",
        ),
        migrations.AddField(
            model_name="mvp",
            name="associates",
            field=models.ManyToManyField(
                related_name="associates", to="website.employee"
            ),
        ),
    ]
