# Generated by Django 5.0.3 on 2024-07-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0013_mvp_development_starting_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="planning_starting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
