# Generated by Django 5.0.3 on 2024-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0015_remove_mvp_planning_starting_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
