# Generated by Django 5.0.3 on 2024-07-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0016_mvp_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvp",
            name="current_phase",
            field=models.CharField(
                choices=[("MVP", "MVP"), ("Product", "Product")], max_length=100
            ),
        ),
    ]
