# Generated by Django 5.0.3 on 2024-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0017_alter_mvp_current_phase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mvp",
            name="is_active",
        ),
        migrations.AddField(
            model_name="mvp",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pause", "Pause"),
                    ("Completed", "Completed"),
                    ("Active", "Active"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
