# Generated by Django 5.0.3 on 2024-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0018_remove_mvp_is_active_mvp_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvp",
            name="current_phase",
            field=models.CharField(
                choices=[("MVP", "MVP"), ("Product", "Product"), ("Failed", "Failed")],
                default="MVP",
                max_length=100,
            ),
        ),
    ]
