# Generated by Django 5.0.3 on 2024-07-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0019_alter_mvp_current_phase"),
        ("website", "0025_alter_employee_mvp_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.employee",
            ),
        ),
    ]
