# Generated by Django 5.0.3 on 2024-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0020_activity_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="first_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
