# Generated by Django 5.0.3 on 2024-07-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0021_mvp_first_completion_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="notes",
            new_name="changes",
        ),
        migrations.AddField(
            model_name="activity",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
