# Generated by Django 5.0.3 on 2024-07-19 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0022_rename_notes_activity_changes_activity_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="created_by",
        ),
    ]
