# Generated by Django 5.0.3 on 2024-07-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0023_remove_activity_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
