# Generated by Django 5.0.3 on 2024-07-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0024_activity_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="changes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
