# Generated by Django 5.0.3 on 2024-07-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0026_activity_created_by"),
        ("website", "0028_alter_employee_confirmation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Success", "Success"),
                            ("Fail", "Fail"),
                            ("Pending", "Pending"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.teams"
                    ),
                ),
            ],
        ),
    ]
