# Generated by Django 5.0.3 on 2024-07-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0027_shortupdate"),
        ("website", "0028_alter_employee_confirmation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortupdate",
            name="created_at",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shortupdate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.employee",
            ),
        ),
    ]
