# Generated by Django 5.0.3 on 2024-09-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MVP", "0030_alter_mvp_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvp",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
